key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwamlsYnRvYWNheG5paWJ2Zml2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczNDAwNDcsImV4cCI6MjA2MjkxNjA0N30.HcJxjirJzpWt8LGjSm72oMDi00B8HnqMC3y8TNgVv98"
url = "https://rpjilbtoacaxniibvfiv.supabase.co"
